title: Shayan Khaksar | A computer enthustiast
description: > # this means to ignore newlines until "baseurl:"
    Shayan Khaksar Personal Blog
permalink: '/blog/:title/'
baseurl: "/en" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shayan Khaksar # add your name
author-img: shayan-khaksar.jpg # add your photo
author-phone: (+98) 000 000 0000
author-country: Iran
author-city: Ahvaz
about-author: Hi, I'm an Android Developer most of the times. Currently studying Computer Engeering. Love almost everything about Computer Science stuff. I mostly write about computer science and programming topics. # add description
social-twitter: sh_khaksar # add your Twitter handle
social-facebook: sh.khaksar # add your Facebook handle
social-github: shkhaksar # add your Github handle
social-linkedin: shkhaksar # add your Linkedin handle
social-instagram: sh.khaksar
social-email: sh.khaksar@yahoo.com # add your Email address

#timezone
timezone: Asia/Tehran

# Disqus
discus-identifier: shkhaksar # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"
